// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBn0HHuYeTuEbJ8y0nLndO01bFD8JnwwuQ',
    appId: '1:787942514303:web:50a17be73d1f17b494e94a',
    messagingSenderId: '787942514303',
    projectId: 'foxyspa-222024',
    authDomain: 'foxyspa-222024.firebaseapp.com',
    storageBucket: 'foxyspa-222024.appspot.com',
    measurementId: 'G-TGTSB38KGC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3EZMb01W2eb4lQSoF46mS4KC8fc2wIvM',
    appId: '1:787942514303:android:2949f5f6baf320a894e94a',
    messagingSenderId: '787942514303',
    projectId: 'foxyspa-222024',
    storageBucket: 'foxyspa-222024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4PvQuQziTUXXV1Aylo-7MecrgWVIw_N0',
    appId: '1:787942514303:ios:b4d6a4ed5300075d94e94a',
    messagingSenderId: '787942514303',
    projectId: 'foxyspa-222024',
    storageBucket: 'foxyspa-222024.appspot.com',
    iosBundleId: 'com.example.spaBookingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4PvQuQziTUXXV1Aylo-7MecrgWVIw_N0',
    appId: '1:787942514303:ios:b4d6a4ed5300075d94e94a',
    messagingSenderId: '787942514303',
    projectId: 'foxyspa-222024',
    storageBucket: 'foxyspa-222024.appspot.com',
    iosBundleId: 'com.example.spaBookingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBn0HHuYeTuEbJ8y0nLndO01bFD8JnwwuQ',
    appId: '1:787942514303:web:c4dbd217b9f5a11394e94a',
    messagingSenderId: '787942514303',
    projectId: 'foxyspa-222024',
    authDomain: 'foxyspa-222024.firebaseapp.com',
    storageBucket: 'foxyspa-222024.appspot.com',
    measurementId: 'G-KV5FLYQBJX',
  );
}
